[package]
name = "int_ratio"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "The type of ratios represented by two integers."
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/int_ratio"
documentation = "https://docs.rs/int_ratio"
keywords = ["ratio", "fraction", "integer", "approximation"]
categories = ["mathematics"]

[dependencies]
